src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Un compte avec cet email existe déjà.")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=Contact::class, mappedBy="user")
     */
    private $contacts;

    /**
     * @ORM\Column(type="smallint")
     */
    private $active = 0;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $token;

    /**
     * @ORM\OneToMany(targetEntity=Article::class, mappedBy="user")
     */
    private $articles;


    public function __construct() {
        $this->createdAt = new \DateTime();
        $this->contacts = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }


    public function getFullname() {
        return $this->firstname.' '.$this->lastname;
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Contact[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setUser($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->contains($contact)) {
            $this->contacts->removeElement($contact);
            // set the owning side to null (unless already changed)
            if ($contact->getUser() === $this) {
                $contact->setUser(null);
            }
        }

        return $this;
    }

    public function getActive(): ?int
    {
        return $this->active;
    }

    public function setActive(int $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(string $token): self
    {
        $this->token = $token;

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setUser($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->contains($article)) {
            $this->articles->removeElement($article);
            // set the owning side to null (unless already changed)
            if ($article->getUser() === $this) {
                $article->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class BlogController extends AbstractController
{
    /**
     * @Route("/blog", name="blog_list")
     */
    public function blog_list(ArticleRepository $articleRepository)
    {
        return $this->render('blog/blog_list.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/blog/{slug}", name="blog_single")
     */
    public function blog_single(Article $article)
    {
        return $this->render('blog/blog_single.html.twig', [
            'article' => $article
        ]);
    }

    /**
     * @Route("/espace-membre/blog/nouvel-article/{slug}", name="blog_new")
     */
    public function blog_new(
        // Le ParamConverter converti $slug en Article
        // Le ? dit que $article = Article|null
        ?Article $article,
        Request $request,
        SluggerInterface $slugger
    ) {
        // Si il y a un article et que l'auteur de l'article N'EST PAS le user connecté --> Exception !!
        if ($article && $article->getUser() !== $this->getUser()) {
            throw new \Exception("Vous n'avez pas le droit de modifier cet article");
        }

        // Si aucun article n'a été trouvé..
        // .. Utiliser une nouvelle instance d'Article
        $new = false;
        if (!$article) {
            $article = new Article();
            $new = true;
        }

        // if ($id) {
        //     $article = $articleRepository->find($id);
        //     if (!$article) {
        //         // return $this->redirectToRoute('blog_new', [ 'id' => 0 ]);
        //         throw new NotFoundHttpException("L'article n'a pas été trouvé");
        //     }
        // }else{
        //     $article = new Article();
        // }

        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if ($new) {
                // On transforme le titre en slug
                $slug = $slugger->slug($article->getTitle());
                $article
                    ->setSlug($slug)
                    ->setUser( $this->getUser() )
                ;
            }
            
            $em = $this->getDoctrine()->getManager();
            $em->persist($article);
            $em->flush();
            $this->addFlash('success', "L'article a bien été ". ($new ? 'créé' : 'modifié') .".");
            return $this->redirectToRoute('blog_new', [ 'slug' => $article->getSlug() ]);
        }

        return $this->render('blog/blog_new.html.twig', [
            'form' => $form->createView(),
            'new' => $new,
            'article' => $article,
        ]);
    }

}

templates/blog/blog_list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon blog{% endblock %}

{% block body %}

    <div class="jumbotron">
        <h1 class="display-4">Mon blog</h1>
        <p class="lead">Je vous parle de ma vie</p>
        <hr class="my-4">
    </div>

    <div class="row">
        {% for article in articles %}
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ article.title }}</h5>
                        <p class="card-text">{{ article.text|nl2br }}</p>
                        <a href="{{ path('blog_single', { slug: article.slug }) }}" class="btn btn-primary">Lire</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/blog/blog_new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon blog{% endblock %}

{% block body %}

    <div class="jumbotron">
        {% if not new %}
            <a href="{{ path('blog_single', { slug: article.slug }) }}" class="float-right">Voir l'article --></a>
        {% endif %}
        <h1 class="display-4">
            {{ new ? 'Nouvel Article' : article.title }}
        </h1>
        {% include '_partials/flash.html.twig' %}
        <hr class="my-4">
    </div>

    {# FORM #}
    {{ form_start(form) }}

    {{ form_widget(form) }}

{#    <div class="row">#}
{#        <div class="col-lg-10">#}
{#            {{ form_row(form.title) }}#}
{#        </div>#}
{#        <div class="col-lg-2 pt-4">#}
{#            <button type="submit" class="btn btn-primary">Valider</button>#}
{#        </div>#}
{#    </div>#}

{#    {{ form_row(form.text) }}#}

     <button type="submit" class="btn btn-primary">Valider</button>

    {{ form_end(form) }}

{% endblock %}

templates/blog/blog_single.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BlogController!{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-lg-8 mx-auto">

            <div class="jumbotron">

                {# Si l'article == le user connecté #}
                {% if article.user == app.user %}
                    <a href="{{ path('blog_new', { slug: article.slug }) }}" class="float-right">Modifier --></a>
                {% endif %}

                <a href="{{ path('blog_list') }}"><-- Retour au blog</a>
                <h1 class="display-4">{{ article.title }}</h1>
                <hr class="my-4">
            </div>

            <div>
                {{ article.text|nl2br }}
            </div>

            <div class="mt-5">
                <hr>
                <i>Auteur : {{ article.user.fullname }}</i>
            </div>

        </div>
    </div>

{% endblock %}